/******************************************************************************/
/***          Generated by IBExpert 2022.3.4.1 07.12.2024 13:06:18          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

CREATE DATABASE 'D:\44\OMIS.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 4096
DEFAULT CHARACTER SET NONE;



/******************************************************************************/
/***                                Domains                                 ***/
/******************************************************************************/

CREATE DOMAIN D_AVATAR AS
BLOB SUB_TYPE 0 SEGMENT SIZE 100;

CREATE DOMAIN D_BOOLEAN AS
SMALLINT
DEFAULT 0
NOT NULL;

CREATE DOMAIN D_DATE AS
DATE;

CREATE DOMAIN D_DEPARTMENT_NAME AS
VARCHAR(50);

CREATE DOMAIN D_DOLGNOST AS
VARCHAR(50);

CREATE DOMAIN D_EMAIL AS
VARCHAR(50);

CREATE DOMAIN D_FAMILIYA AS
VARCHAR(50);

CREATE DOMAIN D_ID AS
INTEGER
NOT NULL;

CREATE DOMAIN D_IMYA AS
VARCHAR(50);

CREATE DOMAIN D_OTCHESTVO AS
VARCHAR(50);

CREATE DOMAIN D_PPRODUCT_DESCRIPTION AS
VARCHAR(100);

CREATE DOMAIN D_PRODUCTS_IMMAGE AS
BLOB SUB_TYPE 0 SEGMENT SIZE 100;

CREATE DOMAIN D_PRODUCT_CATEGORY AS
VARCHAR(50);

CREATE DOMAIN D_PRODUCT_COUNT AS
DOUBLE PRECISION;

CREATE DOMAIN D_PRODUCT_NAME AS
VARCHAR(50);

CREATE DOMAIN D_TEGS_AND_ATRIBUTES AS
VARCHAR(100);

CREATE DOMAIN D_USERNAME AS
VARCHAR(20);

CREATE DOMAIN D_USER_PASSWORD AS
VARCHAR(20);

CREATE DOMAIN D_USER_ROLE AS
VARCHAR(20);



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GEN_TB_PRODUCTS_ID;
SET GENERATOR GEN_TB_PRODUCTS_ID TO 4;

CREATE GENERATOR GEN_TB_USER_ID;
SET GENERATOR GEN_TB_USER_ID TO 31;



/******************************************************************************/
/***                           Stored procedures                            ***/
/******************************************************************************/



SET TERM ^ ;

CREATE PROCEDURE SP_CHECK_LOGIN (
    VUSERNAME D_USERNAME,
    VUSERPASSWORD D_USER_PASSWORD)
RETURNS (
    IS_LOGIN D_BOOLEAN,
    USER_ID INTEGER)
AS
BEGIN
  SUSPEND;
END^






SET TERM ; ^



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE TB_PRODUCTS (
    ID                    D_ID NOT NULL,
    PRODUCT_NAME          D_PRODUCT_NAME,
    PPRODUCT_DESCRIPTION  D_PPRODUCT_DESCRIPTION,
    PRODUCT_COUNT         D_PRODUCT_COUNT,
    PRODUCT_CATEGORY      D_PRODUCT_CATEGORY,
    TEGS_AND_ATRIBUTES    D_TEGS_AND_ATRIBUTES,
    PRODUCTS_IMMAGE       D_PRODUCTS_IMMAGE
);

CREATE TABLE TB_USER (
    ID                             D_ID NOT NULL,
    USERNAME                       D_USERNAME,
    USER_PASSWORD                  D_USER_PASSWORD,
    EMAIL                          D_EMAIL,
    DATE_OF_BIRTH                  D_DATE,
    AVATAR                         D_AVATAR,
    USER_ROLE                      D_USER_ROLE,
    IS_TWO_FACTOR_AUTENTIFICATION  D_BOOLEAN,
    FAMILIYA                       D_FAMILIYA,
    IMYA                           D_IMYA,
    OTCHESTVO                      D_OTCHESTVO,
    DEPARTMENT_NAME                D_DEPARTMENT_NAME,
    DOLGNOST                       D_DOLGNOST
);

INSERT INTO TB_PRODUCTS (ID, PRODUCT_NAME, PPRODUCT_DESCRIPTION, PRODUCT_COUNT, PRODUCT_CATEGORY, TEGS_AND_ATRIBUTES) VALUES (2, 'Товар1', 'Товарный2', 3, 'Перефирия', 'Товар22');


COMMIT WORK;

INSERT INTO TB_USER (ID, USERNAME, USER_PASSWORD, EMAIL, DATE_OF_BIRTH, USER_ROLE, IS_TWO_FACTOR_AUTENTIFICATION, FAMILIYA, IMYA, OTCHESTVO, DEPARTMENT_NAME, DOLGNOST) VALUES (1, 'Admin', 'admin', 'admin@company.by', '2000-01-01', 'Admin', 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TB_USER (ID, USERNAME, USER_PASSWORD, EMAIL, DATE_OF_BIRTH, USER_ROLE, IS_TWO_FACTOR_AUTENTIFICATION, FAMILIYA, IMYA, OTCHESTVO, DEPARTMENT_NAME, DOLGNOST) VALUES (17, 'User1', '1234', 'user@user.by', '2020-12-01', 'User', 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TB_USER (ID, USERNAME, USER_PASSWORD, EMAIL, DATE_OF_BIRTH, USER_ROLE, IS_TWO_FACTOR_AUTENTIFICATION, FAMILIYA, IMYA, OTCHESTVO, DEPARTMENT_NAME, DOLGNOST) VALUES (18, 'User2', '1234', 'user@user.by', '2020-12-01', 'User', 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TB_USER (ID, USERNAME, USER_PASSWORD, EMAIL, DATE_OF_BIRTH, USER_ROLE, IS_TWO_FACTOR_AUTENTIFICATION, FAMILIYA, IMYA, OTCHESTVO, DEPARTMENT_NAME, DOLGNOST) VALUES (19, 'User2', '1234', 'user@user.by', '2020-12-01', 'User', 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TB_USER (ID, USERNAME, USER_PASSWORD, EMAIL, DATE_OF_BIRTH, USER_ROLE, IS_TWO_FACTOR_AUTENTIFICATION, FAMILIYA, IMYA, OTCHESTVO, DEPARTMENT_NAME, DOLGNOST) VALUES (14, 'User3', '1', 'user@user.by', '2020-12-01', 'User', 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TB_USER (ID, USERNAME, USER_PASSWORD, EMAIL, DATE_OF_BIRTH, USER_ROLE, IS_TWO_FACTOR_AUTENTIFICATION, FAMILIYA, IMYA, OTCHESTVO, DEPARTMENT_NAME, DOLGNOST) VALUES (20, 'User2', '1234', 'user@user.by', '2020-12-01', 'User', 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TB_USER (ID, USERNAME, USER_PASSWORD, EMAIL, DATE_OF_BIRTH, USER_ROLE, IS_TWO_FACTOR_AUTENTIFICATION, FAMILIYA, IMYA, OTCHESTVO, DEPARTMENT_NAME, DOLGNOST) VALUES (21, 'User2', '1234', 'user@user.by', '2020-12-01', 'User', 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TB_USER (ID, USERNAME, USER_PASSWORD, EMAIL, DATE_OF_BIRTH, USER_ROLE, IS_TWO_FACTOR_AUTENTIFICATION, FAMILIYA, IMYA, OTCHESTVO, DEPARTMENT_NAME, DOLGNOST) VALUES (22, 'User2', '1234', 'user@user.by', '2020-12-01', 'User', 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TB_USER (ID, USERNAME, USER_PASSWORD, EMAIL, DATE_OF_BIRTH, USER_ROLE, IS_TWO_FACTOR_AUTENTIFICATION, FAMILIYA, IMYA, OTCHESTVO, DEPARTMENT_NAME, DOLGNOST) VALUES (23, 'User2', '1234', 'user@user.by', '2020-12-01', 'User', 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TB_USER (ID, USERNAME, USER_PASSWORD, EMAIL, DATE_OF_BIRTH, USER_ROLE, IS_TWO_FACTOR_AUTENTIFICATION, FAMILIYA, IMYA, OTCHESTVO, DEPARTMENT_NAME, DOLGNOST) VALUES (24, 'User2', '1234', 'user@user.by', '2020-12-01', 'User', 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TB_USER (ID, USERNAME, USER_PASSWORD, EMAIL, DATE_OF_BIRTH, USER_ROLE, IS_TWO_FACTOR_AUTENTIFICATION, FAMILIYA, IMYA, OTCHESTVO, DEPARTMENT_NAME, DOLGNOST) VALUES (25, 'User2', '1234', 'user@user.by', '2020-12-01', 'User', 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TB_USER (ID, USERNAME, USER_PASSWORD, EMAIL, DATE_OF_BIRTH, USER_ROLE, IS_TWO_FACTOR_AUTENTIFICATION, FAMILIYA, IMYA, OTCHESTVO, DEPARTMENT_NAME, DOLGNOST) VALUES (26, 'User2', '1234', 'user@user.by', '2020-12-01', 'User', 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TB_USER (ID, USERNAME, USER_PASSWORD, EMAIL, DATE_OF_BIRTH, USER_ROLE, IS_TWO_FACTOR_AUTENTIFICATION, FAMILIYA, IMYA, OTCHESTVO, DEPARTMENT_NAME, DOLGNOST) VALUES (27, 'User2', '1234', 'user@user.by', '2020-12-01', 'User', 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TB_USER (ID, USERNAME, USER_PASSWORD, EMAIL, DATE_OF_BIRTH, USER_ROLE, IS_TWO_FACTOR_AUTENTIFICATION, FAMILIYA, IMYA, OTCHESTVO, DEPARTMENT_NAME, DOLGNOST) VALUES (31, 'Login', 'Password', '', '2021-01-31', 'User', 0, 'Иванов', 'Иван', 'Иванович', 'Бухгалтерия', NULL);


COMMIT WORK;



/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE TB_PRODUCTS ADD CONSTRAINT PK_TB_PRODUCTS PRIMARY KEY (ID);
ALTER TABLE TB_USER ADD CONSTRAINT PK_TB_USER PRIMARY KEY (ID);


/******************************************************************************/
/***                           Stored procedures                            ***/
/******************************************************************************/



SET TERM ^ ;

ALTER PROCEDURE SP_CHECK_LOGIN (
    VUSERNAME D_USERNAME,
    VUSERPASSWORD D_USER_PASSWORD)
RETURNS (
    IS_LOGIN D_BOOLEAN,
    USER_ID INTEGER)
AS
begin
  is_login=0;
  user_id=-1;
  for select tb_user.id
        from tb_user
        where tb_user.username=:vusername
          and tb_user.user_password=:vuserpassword
      into :user_id
  do
    begin
      is_login=1;
    end
  suspend;
/* Procedure Text */
end^



SET TERM ; ^



/******************************************************************************/
/***                              Descriptions                              ***/
/******************************************************************************/

DESCRIBE DOMAIN D_AVATAR
'Домен аватара';

DESCRIBE DOMAIN D_BOOLEAN
'Домен для логических значений';

DESCRIBE DOMAIN D_DATE
'Домен для дат';

DESCRIBE DOMAIN D_DEPARTMENT_NAME
'Домен названия структурного подраделения';

DESCRIBE DOMAIN D_DOLGNOST
'Должность';

DESCRIBE DOMAIN D_EMAIL
'Домен электронной почты';

DESCRIBE DOMAIN D_FAMILIYA
'Домен фамилии';

DESCRIBE DOMAIN D_ID
'Домен первичного ключа';

DESCRIBE DOMAIN D_IMYA
'Домен имени';

DESCRIBE DOMAIN D_OTCHESTVO
'Домен отчества';

DESCRIBE DOMAIN D_PPRODUCT_DESCRIPTION
'Домен описания товара';

DESCRIBE DOMAIN D_PRODUCTS_IMMAGE
'Домен изображения продукции';

DESCRIBE DOMAIN D_PRODUCT_CATEGORY
'Домен категории товаров';

DESCRIBE DOMAIN D_PRODUCT_COUNT
'Домен количества товаров';

DESCRIBE DOMAIN D_PRODUCT_NAME
'Домен названия товара';

DESCRIBE DOMAIN D_TEGS_AND_ATRIBUTES
'Домен задания тэгов и атрибутов';

DESCRIBE DOMAIN D_USERNAME
'Домен имени пользователя';

DESCRIBE DOMAIN D_USER_PASSWORD
'Домен пароля пользователя';

DESCRIBE DOMAIN D_USER_ROLE
'Домен роли пользователя';



/******************************************************************************/
/***                              Descriptions                              ***/
/******************************************************************************/

DESCRIBE TABLE TB_PRODUCTS
'Таблица товаров';

DESCRIBE TABLE TB_USER
'Таблица пользователей';



/******************************************************************************/
/***                              Descriptions                              ***/
/******************************************************************************/

DESCRIBE GENERATOR GEN_TB_USER_ID
'Генератор значений первичного ключа таблицы TB_User по полю ID';



/******************************************************************************/
/***                          Fields descriptions                           ***/
/******************************************************************************/

DESCRIBE FIELD ID TABLE TB_PRODUCTS
'Домен первичного ключа';

DESCRIBE FIELD PRODUCT_NAME TABLE TB_PRODUCTS
'Название товара';

DESCRIBE FIELD PPRODUCT_DESCRIPTION TABLE TB_PRODUCTS
'Описание товара';

DESCRIBE FIELD PRODUCT_COUNT TABLE TB_PRODUCTS
'Количество товаров';

DESCRIBE FIELD PRODUCT_CATEGORY TABLE TB_PRODUCTS
'Категория товаров';

DESCRIBE FIELD TEGS_AND_ATRIBUTES TABLE TB_PRODUCTS
'Тэги и атрибуты';

DESCRIBE FIELD PRODUCTS_IMMAGE TABLE TB_PRODUCTS
'Изображение продукции';

DESCRIBE FIELD ID TABLE TB_USER
'первичный ключ';

DESCRIBE FIELD USERNAME TABLE TB_USER
'Логин пользователя';

DESCRIBE FIELD USER_PASSWORD TABLE TB_USER
'Пароль пользователя';

DESCRIBE FIELD EMAIL TABLE TB_USER
'Электронная почта';

DESCRIBE FIELD DATE_OF_BIRTH TABLE TB_USER
'День рождения';

DESCRIBE FIELD AVATAR TABLE TB_USER
'Аватар';

DESCRIBE FIELD USER_ROLE TABLE TB_USER
'Роль пользователя';

DESCRIBE FIELD IS_TWO_FACTOR_AUTENTIFICATION TABLE TB_USER
'Нужна двухфакторная авториззация?';

DESCRIBE FIELD FAMILIYA TABLE TB_USER
'Фамилия пользователя';

DESCRIBE FIELD IMYA TABLE TB_USER
'Имя собственное пользователя';

DESCRIBE FIELD OTCHESTVO TABLE TB_USER
'Отчество пользователя';

DESCRIBE FIELD DEPARTMENT_NAME TABLE TB_USER
'название структурного подраделения';

DESCRIBE FIELD DOLGNOST TABLE TB_USER
'Должность';

